### ISSUE TITLE
Issue while downloading

### ISSUE THREAD

**Issue by saurabh-gohil** [IAmBlackHacker/Video-Downloader#1]
Getting the following error while trying to download using Windows 7 and python 3
 No plugin can handle URL: https://staragvod-vh.akamaihd.net/i/videos/lifeok/dekedema/412_1/1000000626_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/master.m3u8?hdnea=st=1532167202~exp=1532167802~acl=/*~hmac=556f2605f6e2cb4f57c5d59d7cc737293686646815f6d2937b3d8098b32f35bd

Please help

**Comment by krishnenduash** [comment]
not working in windows .

**Comment by IAMMADHACKER** [comment]
Is it working in Linux

**Comment by IAMMADHACKER** [comment]
Hi I need help from you contact me at Telegram @UnknownHacker2 And tell me how to setup this script on pc and support me to download videos from Hotstar and YouTube

**Comment by IAmBlackHacker** [comment]
Actually service is not available on-site now, is anyone can update with new script

**Comment by IAmBlackHacker** [comment]
Welcome contributors
